package it.polimi.ingsw.GC_29.Components;

/**
 * Created by Lorenzotara on 12/06/17.
 */
public enum SpecialBonusAndMalus {

    PAWNONOCCUPIEDSPACE,
    FREETOWER,
    FIVEVICTORYPOINTSIFPRAY,
    NOMILITARYFORTERRITORY,
    X2ONIMMEDIATE,
    NOMARKET,
    NOGREENTOWER,
    NOBLUETOWER,
    NOYELLOWTOWER,
    NOPURPLETOWER,
    NOCOUNCILPALACE,
    NOHARVEST,
    NOPRODUCTION,
    TWOWORKERS,
    NOVICTORYFROMBLUE,
    NOVICTORYFROMPURPLE,
    NOVICTORYFROMGREEN,
    CHANGEVALUEOFEVERYPAWN,
    CHANGEVALUEOFONEPAWN,
    SKIPFIRSTTURN
}
