package it.polimi.ingsw.GC_29.Controllers;

/**
 * Created by Christian on 07/06/2017.
 */
public enum PlayerState {

    THROWDICES,
    DOACTION,
    CHOOSEACTION,
    BONUSACTION,
    ENDTURN,
    PRAY,
    WAITING,
    CHOOSEWORKERS,
    CHOOSE_EFFECT,
    CHOOSE_COUNCIL_PRIVILEGE,
    CHOOSECOST,
    CHOOSE_BONUS_TILE, SUSPENDED, DISCARDINGLEADER, LEADER, ACTIVATE_PAY_TO_OBTAIN_CARDS
}
